# ===============================
# Configuración de Base de Datos
# ===============================
spring.datasource.url=jdbc:postgresql://192.168.1.200:5433/lexflow_db
spring.datasource.username=lexflow_admin
spring.datasource.password=rootpassword123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# Configuración de JPA / Hibernate
# ===============================
# 'update' creará las tablas automáticamente basándose en tus clases de Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostrar el SQL en la consola para ver qué hace por detrás
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# ===============================
# Configuración de Swagger
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs


# Límite por cada archivo individual
spring.servlet.multipart.max-file-size=50MB

# Límite total de la petición (por si suben varios archivos a la vez)
spring.servlet.multipart.max-request-size=50MB

spring.jackson.mapper.accept-case-insensitive-enums=true

# --- CREDENCIALES DE GOOGLE DRIVE ---
google.drive.client-id=407279297597-v1qk59ibq1pls0416jujfbbsdd6qtdu2.apps.googleusercontent.com
google.drive.client-secret=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
google.drive.refresh-token=1//04xA4Tudqo0mqCgYIARAAGAQSNwF-L9IrdNIEItUvSxD0mFdedf9AzfdlVoqFh6GwCCHKokcGuLOeh6_cdlKcOZWOrRqXv0GKfEg
google.drive.folder-id=1658bl-PsTh3_MDsbjjBG6n6LVaLupgI6


cloud.aws.s3.endpoint=http://192.168.1.200:9000
cloud.aws.s3.access-key=adminLexFlow
cloud.aws.s3.secret-key=SuperSecretPassword123
cloud.aws.s3.bucket-name=lexflow-archivos
cloud.aws.s3.region=us-east-1