# ===============================
# Configuración de Base de Datos
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/lexflow_db
spring.datasource.username=lexflow_admin
spring.datasource.password=rootpassword123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# Configuración de JPA / Hibernate
# ===============================
# 'update' creará las tablas automáticamente basándose en tus clases de Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostrar el SQL en la consola para ver qué hace por detrás
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# ===============================
# Configuración de Swagger
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs